"""Testnet Sampling Lane state manager (plan section 10.2).

This module manages the stateful throttles that keep the sampling lane from
flooding the exchange with test orders while still providing enough signal-path
coverage:

- Per-symbol daily trade count (max_daily_trades_per_symbol).
- Per-symbol cooldown (seconds since the last entry in that symbol).
- Account-wide daily trade cap (max_daily_trades_total).

The rules are applied BEFORE entry is submitted. The candidate itself is
generated by ``testnet_sampling_v2.generate_sampling_candidate``.

Design note: state is held in-memory and scoped to one Scheduler process.
Persistence is through the repository (last entry timestamps). On restart the
counts reset to zero, which is acceptable because the limits are conservative
by design and a brief over-limit on restart is less harmful than a complex
shared-state system.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class SamplingState:
    """Mutable sampling lane throttle state for one Scheduler process."""

    # Mapping from symbol to count of entries on the current calendar day (UTC).
    daily_symbol_counts: dict[str, int] = field(default_factory=dict)
    # Mapping from symbol to UTC timestamp of the last entry.
    last_entry_at: dict[str, datetime | None] = field(default_factory=dict)
    # The UTC date for which the daily counters were last reset.
    last_reset_date: datetime | None = None
    # Total entries across all symbols on the current day.
    daily_total_count: int = 0

    def record_entry(self, symbol: str, at: datetime) -> None:
        """Record a sampling entry for *symbol* at *at*."""
        self._maybe_reset(at)
        self.daily_symbol_counts[symbol] = self.daily_symbol_counts.get(symbol, 0) + 1
        self.daily_total_count += 1
        self.last_entry_at[symbol] = at

    def _maybe_reset(self, now: datetime) -> None:
        today = now.date()
        if self.last_reset_date is None or self.last_reset_date.date() != today:
            self.daily_symbol_counts = {}
            self.daily_total_count = 0
            self.last_reset_date = now


@dataclass(frozen=True)
class SamplingThrottleResult:
    """Decision from the sampling throttle check."""

    allowed: bool
    reason: str = ""


def check_sampling_throttle(
    symbol: str,
    now: datetime,
    state: SamplingState,
    *,
    max_daily_trades_per_symbol: int = 3,
    max_daily_trades_total: int = 6,
    cooldown_seconds: int = 900,
) -> SamplingThrottleResult:
    """Decide whether the sampling lane may enter *symbol* at *now*.

    Args:
        symbol: Trading symbol, e.g. ``"BTC/USDT"``.
        now: Current UTC timestamp.
        state: Mutable throttle state owned by the caller (Scheduler).
        max_daily_trades_per_symbol: Hard cap on entries per symbol per calendar day.
        max_daily_trades_total: Hard cap on total entries across all symbols per day.
        cooldown_seconds: Minimum seconds since the last entry in this symbol.

    Returns:
        SamplingThrottleResult.
    """
    state._maybe_reset(now)

    # Daily per-symbol cap.
    symbol_count = state.daily_symbol_counts.get(symbol, 0)
    if symbol_count >= max_daily_trades_per_symbol:
        return SamplingThrottleResult(
            allowed=False,
            reason=f"{symbol} daily sampling cap reached ({symbol_count}/{max_daily_trades_per_symbol})",
        )

    # Daily total cap.
    if state.daily_total_count >= max_daily_trades_total:
        return SamplingThrottleResult(
            allowed=False,
            reason=f"total daily sampling cap reached ({state.daily_total_count}/{max_daily_trades_total})",
        )

    # Per-symbol cooldown.
    last_at = state.last_entry_at.get(symbol)
    if last_at is not None:
        elapsed = (now - last_at).total_seconds()
        if elapsed < cooldown_seconds:
            remaining = cooldown_seconds - elapsed
            return SamplingThrottleResult(
                allowed=False,
                reason=f"{symbol} in cooldown ({remaining:.0f}s remaining)",
            )

    return SamplingThrottleResult(allowed=True)
