"""Unified platform data contracts (single source of truth for all layers).

Import from here, never redefine these shapes inside a service:

    from shared.models import OHLCVBar, BacktestReport, RiskEvent
"""

from __future__ import annotations

from .alpha import AlphaOperator, AlphaPlan
from .api import ApiError, CollectionResponse, TaskSubmission
from .backtest import (
    GATE_MAX_DRAWDOWN,
    GATE_MIN_EXPECTANCY,
    GATE_MIN_PROFIT_FACTOR,
    GATE_MIN_SHARPE,
    BacktestReport,
    GateDecision,
)
from .base import PlatformModel
from .decision_memory import DecisionMemoryEntry
from .enums import (
    BacktestEngine,
    BetDecision,
    EnsembleStatus,
    Exchange,
    Market,
    RiskEventType,
    RiskLevel,
    RiskResolutionStatus,
    RiskSeverity,
    RunStatus,
    StrategyStatus,
    Timeframe,
    TradeSide,
    TripleBarrierOutcome,
)
from .execution_runtime import (
    ExchangeAccountSnapshot,
    ExchangeGatewayCapability,
    ReconciliationRecord,
    TradingRuntimeStatus,
)
from .macro import MacroEvent
from .market import (
    ConsoleOverview,
    ExchangeCapability,
    FundingArbitrageSignal,
    MarketExtras,
    MarketOrderBookResponse,
    MarketSnapshot,
    MarketTrade,
    MarketTradesResponse,
    MarketUniverseItem,
    OHLCVBar,
    OhlcvSeriesResponse,
    OrderBookLevel,
)
from .research_source import (
    ResearchSourceAsset,
    ResearchSourceIdeaExtractionRequest,
    ResearchSourceImportRequest,
    ResearchSourceImportResult,
    StrategySourceManifest,
)
from .risk import RiskEvent, RiskEventResolutionUpdate, RiskProfile
from .signal import (
    CandidateSignalSeries,
    DecisionVetoResult,
    MetaLabel,
    MetaLabelRequest,
    MetaLabelSample,
    SignalEnsemble,
    SignalEnsembleRequest,
    SignalVote,
    TradeSignal,
)
from .strategy import (
    StrategyBase,
    StrategyContract,
    StrategyCreate,
    StrategyDraft,
    StrategyIdea,
    StrategyRead,
    StrategyRules,
    StrategyUpdate,
    StrategyVersion,
)
from .validation import HypothesisRecord, PodRiskReport, ValidationBenchmarkResult
from .workflow import (
    AdjustLeverageRequest,
    AgentTask,
    AgentTaskRequest,
    BacktestRun,
    BacktestSubmissionRequest,
    CancelOrderRequest,
    CarryBacktestRequest,
    ClosePositionRequest,
    ExecutionOrderRequest,
    ExecutionRiskState,
    ExecutionSignal,
    FailureRecord,
    IngestionJob,
    IngestionJobRequest,
    LeverageAdjustmentResult,
    LiveRun,
    LiveRunRequest,
    ManualOrderRequest,
    NotificationDeliveryUpdate,
    NotificationOutboxItem,
    OptimizationRun,
    OptimizationSubmissionRequest,
    OrderExecution,
    PaperRun,
    PaperRunRequest,
    PaperRunStatusUpdate,
    PaperRunStepRequest,
    PaperRuntimeAction,
    PaperRuntimeCycleRequest,
    PaperRuntimeCycleResult,
    PaperRuntimeStatus,
    PositionSnapshot,
    ReviewReport,
)

__all__ = [
    # base
    "PlatformModel",
    # enums
    "BacktestEngine",
    "Exchange",
    "Market",
    "RiskEventType",
    "RiskLevel",
    "RiskResolutionStatus",
    "RiskSeverity",
    "RunStatus",
    "StrategyStatus",
    "Timeframe",
    "TradeSide",
    "EnsembleStatus",
    "BetDecision",
    "TripleBarrierOutcome",
    # market
    "OHLCVBar",
    "MarketExtras",
    "MarketSnapshot",
    "OhlcvSeriesResponse",
    "OrderBookLevel",
    "MarketOrderBookResponse",
    "MarketTrade",
    "MarketTradesResponse",
    "ConsoleOverview",
    "ExchangeCapability",
    "MarketUniverseItem",
    "FundingArbitrageSignal",
    # backtest
    "BacktestReport",
    "GateDecision",
    "GATE_MIN_SHARPE",
    "GATE_MIN_PROFIT_FACTOR",
    "GATE_MAX_DRAWDOWN",
    "GATE_MIN_EXPECTANCY",
    "HypothesisRecord",
    "ValidationBenchmarkResult",
    "PodRiskReport",
    # risk
    "RiskEvent",
    "RiskEventResolutionUpdate",
    "RiskProfile",
    "StrategySourceManifest",
    "ResearchSourceAsset",
    "ResearchSourceImportRequest",
    "ResearchSourceIdeaExtractionRequest",
    "ResearchSourceImportResult",
    # macro
    "MacroEvent",
    # signal
    "TradeSignal",
    "CandidateSignalSeries",
    "SignalVote",
    "SignalEnsemble",
    "SignalEnsembleRequest",
    "DecisionVetoResult",
    "MetaLabel",
    "MetaLabelSample",
    "MetaLabelRequest",
    # alpha
    "AlphaOperator",
    "AlphaPlan",
    # api
    "CollectionResponse",
    "TaskSubmission",
    "ApiError",
    # strategy
    "StrategyIdea",
    "StrategyDraft",
    "StrategyVersion",
    "StrategyBase",
    "StrategyContract",
    "StrategyCreate",
    "StrategyUpdate",
    "StrategyRead",
    "StrategyRules",
    "DecisionMemoryEntry",
    "ExchangeGatewayCapability",
    "ExchangeAccountSnapshot",
    "ReconciliationRecord",
    "TradingRuntimeStatus",
    # workflow
    "BacktestRun",
    "BacktestSubmissionRequest",
    "CarryBacktestRequest",
    "OptimizationRun",
    "OptimizationSubmissionRequest",
    "PaperRun",
    "PaperRuntimeAction",
    "PaperRuntimeCycleRequest",
    "PaperRuntimeCycleResult",
    "PaperRuntimeStatus",
    "PaperRunRequest",
    "PaperRunStatusUpdate",
    "PaperRunStepRequest",
    "LiveRun",
    "LiveRunRequest",
    "ExecutionSignal",
    "ExecutionRiskState",
    "ExecutionOrderRequest",
    "ManualOrderRequest",
    "ClosePositionRequest",
    "AdjustLeverageRequest",
    "CancelOrderRequest",
    "LeverageAdjustmentResult",
    "OrderExecution",
    "PositionSnapshot",
    "ReviewReport",
    "FailureRecord",
    "IngestionJob",
    "IngestionJobRequest",
    "AgentTask",
    "AgentTaskRequest",
    "NotificationDeliveryUpdate",
    "NotificationOutboxItem",
]
