"""Regenerate the verification block in CURRENT_STATE.md from a real pytest run.

Why this exists: CURRENT_STATE.md carried a hand-typed line claiming
``474 passed`` dated 2026-07-18 while the suite had long since moved on (and was
in fact red). A hand-maintained number is a claim; a generated one is evidence.

Two input modes, both backed by an actual run:

* ``--junit-xml <path>`` parses counts from a JUnit report. This is the CI path:
  the suite already ran, so nothing is executed twice.
* ``--run`` executes the suite here and parses its own report.

There is deliberately no "just take my word for it" mode that accepts counts as
arguments -- that would recreate the exact failure this script exists to remove.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = REPO_ROOT / "CURRENT_STATE.md"

BEGIN_MARKER = "<!-- BEGIN GENERATED: pytest-verification -->"
END_MARKER = "<!-- END GENERATED: pytest-verification -->"

DEFAULT_PYTEST_ARGS = ("-q", "-m", "not integration")


@dataclass(frozen=True)
class SuiteResult:
    total: int
    failures: int
    errors: int
    skipped: int

    @property
    def passed(self) -> int:
        return self.total - self.failures - self.errors - self.skipped

    @property
    def is_green(self) -> bool:
        return self.failures == 0 and self.errors == 0


def parse_junit(path: Path) -> SuiteResult:
    """Sum counts across testsuite elements of a JUnit XML report."""

    root = ET.parse(path).getroot()  # noqa: S314 - our own pytest output
    suites = [root] if root.tag == "testsuite" else list(root.iter("testsuite"))
    if not suites:
        raise ValueError(f"no <testsuite> element found in {path}")

    def total(attr: str) -> int:
        return sum(int(suite.get(attr, "0") or 0) for suite in suites)

    return SuiteResult(
        total=total("tests"),
        failures=total("failures"),
        errors=total("errors"),
        skipped=total("skipped"),
    )


def run_pytest(report_path: Path) -> SuiteResult:
    completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [sys.executable, "-m", "pytest", *DEFAULT_PYTEST_ARGS, f"--junit-xml={report_path}"],
        cwd=REPO_ROOT,
        check=False,
    )
    if not report_path.exists():
        raise RuntimeError(f"pytest produced no report (exit {completed.returncode}); cannot refresh state")
    return parse_junit(report_path)


def render_block(result: SuiteResult, *, now: datetime) -> str:
    stamp = now.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")
    verdict = "green" if result.is_green else f"RED ({result.failures} failed, {result.errors} error)"
    detail = f"`{result.passed} passed, {result.failures} failed, {result.errors} error, {result.skipped} skipped`"
    return "\n".join(
        [
            BEGIN_MARKER,
            f"Backend pytest (`pytest {' '.join(DEFAULT_PYTEST_ARGS)}`) as of {stamp}: {detail} -- {verdict}.",
            "",
            "This block is generated by `scripts/refresh_current_state.py` from a real run."
            " Do not edit it by hand; a hand-typed count is a claim, not evidence.",
            END_MARKER,
        ]
    )


def splice(text: str, block: str) -> str:
    """Replace an existing generated block, or append one if absent."""

    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(lambda _: block, text, count=1)
    separator = "" if text.endswith("\n") else "\n"
    return f"{text}{separator}\n{block}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--junit-xml", type=Path, help="parse counts from an existing JUnit report")
    source.add_argument("--run", action="store_true", help="run the suite now and parse its report")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file is not already up to date, without writing",
    )
    args = parser.parse_args()

    if args.run:
        with tempfile.TemporaryDirectory() as tmp:
            result = run_pytest(Path(tmp) / "report.xml")
    else:
        if not args.junit_xml.exists():
            print(f"FAIL: report not found: {args.junit_xml}", file=sys.stderr)
            return 1
        result = parse_junit(args.junit_xml)

    original = STATE_FILE.read_text(encoding="utf-8")
    updated = splice(original, render_block(result, now=datetime.now(UTC)))

    if args.check:
        # Compare ignoring the timestamp line, which always moves.
        if _without_timestamp(original) == _without_timestamp(updated):
            print("OK: CURRENT_STATE.md verification block matches the latest run.")
            return 0
        print("FAIL: CURRENT_STATE.md verification block is stale.", file=sys.stderr)
        print("Run: python scripts/refresh_current_state.py --run", file=sys.stderr)
        return 1

    if updated != original:
        STATE_FILE.write_text(updated, encoding="utf-8")
        print(
            f"updated {STATE_FILE.relative_to(REPO_ROOT).as_posix()}: {result.passed} passed, {result.failures} failed"
        )
    else:
        print("no change needed")
    return 0


def _without_timestamp(text: str) -> str:
    return re.sub(r"as of \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC", "as of <stamp>", text)


if __name__ == "__main__":
    raise SystemExit(main())
